create table tb_department (id bigint generated by default as identity, name varchar(255), primary key (id));
create table tb_product (price float(53), department_id bigint, id bigint generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_product add constraint FKi5b17771bifanjax4awtcu63i foreign key (department_id) references tb_department;
INSERT INTO tb_department (name) VALUES ('Eletrônicos');
INSERT INTO tb_department (name) VALUES ('Vestuário');
INSERT INTO tb_department (name) VALUES ('Alimentos');

INSERT INTO tb_product (name, price, department_id) VALUES ('Smartphone', 2000.00, 1);
INSERT INTO tb_product (name, price, department_id) VALUES ('Notebook', 3500.00, 1);
INSERT INTO tb_product (name, price, department_id) VALUES ('Camiseta', 50.00, 2);
INSERT INTO tb_product (name, price, department_id) VALUES ('Calça Jeans', 120.00, 2);
INSERT INTO tb_product (name, price, department_id) VALUES ('Arroz 5kg', 25.00, 3);
